import React, { useState } from 'react';

const ReportViewer = ({ reportData, onReportGenerated }) => {
  const [showReport, setShowReport] = useState(false);
  const [reportContent, setReportContent] = useState('');

  const generateReport = () => {
    setShowReport(true);
    // In a real implementation, this would call the backend to generate a report
    setReportContent(`
WORKFORCE INTELLIGENCE AGENT - ANALYSIS REPORT
Generated: ${new Date().toLocaleString()}
========================================

EXECUTIVE SUMMARY
This report outlines the workforce automation opportunities identified through
analysis of the provided dataset.

KEY FINDINGS
• Analysis completed successfully
• Recommendations for process optimization identified
• Potential FTE savings calculated based on available data

AUTOMATION OPPORTUNITIES
Review the FTE Dashboard for detailed breakdown of top automation candidates.

NEXT STEPS
1. Validate findings with subject matter experts
2. Prioritize high-impact automation opportunities
3. Develop pilot automation projects
4. Measure and track realized savings

========================================
Report generated by WorkForce Intelligence Agent v1.0
Built for FutureAI Global Hackathon 2026
    `);

    // Simulate sending report data back to parent
    onReportGenerated({
      type: 'executive_summary',
      generatedAt: new Date().toISOString(),
      content: reportContent
    });
  };

  return (
    <div className="bg-white rounded-lg shadow-md p-6">
      <h2 className="text-xl font-semibold mb-4">Report Viewer</h2>
      <p className="text-gray-600 mb-4">
        Generate and view executive reports based on analysis results
      </p>

      {!reportData && !showReport ? (
        <div className="text-center py-12">
          <div className="inline-block w-20 h-20 border-4 border-dashed border-gray-300 rounded-full flex items-center justify-center mb-4">
            <svg className="w-10 h-10 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m2 0a2 2 0 110-4 2 2 0 010 4zm-6 0a2 2 0 110-4 2 2 0 010 4zm6 0a2 2 0 100-4 2 2 0 000 4z" />
            </svg>
          </div>
          <p>Generate a report to view insights here</p>
          <button
            onClick={generateReport}
            className="mt-4 bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-lg transition-colors"
          >
            Generate Report
          </button>
        </div>
      ) : (
        <div>
          {showReport && (
            <div className="mb-6">
              <h3 className="text-lg font-semibold mb-4">Generated Report</h3>
              <div className="bg-gray-50 p-4 rounded-lg h-96 overflow-y-auto font-mono text-sm">
                <pre>{reportContent}</pre>
              </div>
              <button
                onClick={() => setShowReport(false)}
                className="bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded-lg transition-colors"
              >
                Close Report
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default ReportViewer;